/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\samay\OneDrive\Desktop\Hobbies_and_skills\dev\Sanatani@nimAtor\Sanatani@nimAtor_web\Animation_with_abhi\public\models\anime_like_waterbody.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function CustomClouds(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/anime_like_waterbody.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0, 3.22, 0]} />
        <group name="Empty001" position={[-11.553, 3.443, -10.3]} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials.sprouts} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['material.002']} position={[1.856, 0, -1.771]} rotation={[-Math.PI, 1.533, -Math.PI]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[2.458, -0.005, -1.187]} rotation={[-2.749, 0, 0]} scale={[-0.002, -0.304, -0.304]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[2.447, 0.074, -1.192]} scale={[0.154, 0.115, 0.154]} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[0.228, 0.074, 0.581]} scale={[0.154, 0.115, 0.154]} />
        <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['material.002']} position={[-2.513, 0, -1.442]} scale={0.433} />
        <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['material.002']} position={[-1.444, 0, -1.856]} scale={0.531} />
        <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={materials['material.002']} position={[-2.158, 0, -3.738]} rotation={[0, Math.PI / 4, 0]} scale={0.653} />
        <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={materials.sprouts} position={[1.327, 1.211, 1.041]} scale={0.343} />
        <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials['material.005']} position={[1.097, 0.989, -3.173]} scale={0.399} />
        <mesh name="Circle007" geometry={nodes.Circle007.geometry} material={materials.sprouts} position={[0.776, -0.097, 0.839]} scale={0.387} />
        <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={materials.sprouts} position={[-1.302, -0.097, -3.17]} rotation={[0, 1.361, 0]} scale={0.764} />
        <mesh name="Circle009" geometry={nodes.Circle009.geometry} material={materials['material.002']} position={[-3.748, 0, -0.271]} rotation={[0, Math.PI / 4, 0]} />
        <mesh name="Circle010" geometry={nodes.Circle010.geometry} material={materials['material.002']} position={[-3.579, 0, -2.707]} rotation={[-Math.PI, 0.747, -Math.PI]} />
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} position={[-2.861, 0.074, -2.843]} rotation={[0, Math.PI / 4, 0]} scale={[0.154, 0.115, 0.154]} />
        <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[-3.176, 0.074, -0.02]} rotation={[0, Math.PI / 4, 0]} scale={[0.154, 0.115, 0.154]} />
        <mesh name="Circle011" geometry={nodes.Circle011.geometry} material={materials['material.002']} position={[-5.933, 0, -2.455]} rotation={[0, Math.PI / 4, 0]} scale={0.741} />
        <mesh name="Circle012" geometry={nodes.Circle012.geometry} material={materials['material.002']} position={[-6.082, 0, -0.562]} rotation={[0, Math.PI / 4, 0]} scale={0.531} />
        <mesh name="Circle013" geometry={nodes.Circle013.geometry} material={materials['material.002']} position={[-7.918, 0, -1.388]} rotation={[0, Math.PI / 2, 0]} scale={0.653} />
        <mesh name="Circle014" geometry={nodes.Circle014.geometry} material={materials.sprouts} position={[-2.074, 1.211, -0.473]} rotation={[0, Math.PI / 4, 0]} scale={0.343} />
        <mesh name="Circle015" geometry={nodes.Circle015.geometry} material={materials.sprouts} position={[-5.217, 0.989, -3.29]} rotation={[0, Math.PI / 4, 0]} scale={0.399} />
        <mesh name="Circle016" geometry={nodes.Circle016.geometry} material={materials.sprouts} position={[-2.607, -0.097, -0.226]} rotation={[0, Math.PI / 4, 0]} scale={0.387} />
        <mesh name="Circle017" geometry={nodes.Circle017.geometry} material={materials.sprouts} position={[-6.91, -0.097, -1.592]} rotation={[-Math.PI, 0.995, -Math.PI]} scale={0.764} />
        <mesh name="Circle018" geometry={nodes.Circle018.geometry} material={materials['material.002']} position={[-2.139, 0, -7.275]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Circle019" geometry={nodes.Circle019.geometry} material={materials['material.002']} position={[-3.742, 0, -9.117]} rotation={[Math.PI, -0.038, Math.PI]} />
        <mesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[-3.331, 0.074, -9.721]} rotation={[0, Math.PI / 2, 0]} scale={[0.154, 0.115, 0.154]} />
        <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={nodes.Sphere005.material} position={[-1.557, 0.074, -7.502]} rotation={[0, Math.PI / 2, 0]} scale={[0.154, 0.115, 0.154]} />
        <mesh name="Circle020" geometry={nodes.Circle020.geometry} material={materials['material.002']} position={[-5.228, 0, -7.275]} rotation={[0, Math.PI / 2, 0]} scale={0.741} />
        <mesh name="Circle021" geometry={nodes.Circle021.geometry} material={nodes.Circle021.material} position={[-3.995, 0, -5.831]} rotation={[0, Math.PI / 2, 0]} scale={0.531} />
        <mesh name="Circle022" geometry={nodes.Circle022.geometry} material={materials['material.002']} position={[-5.877, 0, -5.116]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.653} />
        <mesh name="Circle023" geometry={nodes.Circle023.geometry} material={materials.sprouts} position={[-1.098, 1.211, -8.602]} rotation={[0, Math.PI / 2, 0]} scale={0.343} />
        <mesh name="Circle024" geometry={nodes.Circle024.geometry} material={materials.sprouts} position={[-5.312, 0.989, -8.371]} rotation={[0, Math.PI / 2, 0]} scale={0.399} />
        <mesh name="Circle025" geometry={nodes.Circle025.geometry} material={materials.sprouts} position={[-1.3, -0.097, -8.051]} rotation={[0, Math.PI / 2, 0]} scale={0.387} />
        <mesh name="Circle026" geometry={nodes.Circle026.geometry} material={materials.sprouts} position={[-5.309, -0.097, -5.973]} rotation={[-Math.PI, 0.209, -Math.PI]} scale={0.764} />
        <mesh name="Circle027" geometry={nodes.Circle027.geometry} material={materials['material.002']} position={[0.52, 0.016, -6.008]} rotation={[0, -Math.PI / 2, 0]} scale={0.938} />
        <mesh name="Circle028" geometry={nodes.Circle028.geometry} material={materials['material.002']} position={[2.024, 0.016, -4.279]} rotation={[0, 0.038, 0]} scale={0.938} />
        <mesh name="Sphere006" geometry={nodes.Sphere006.geometry} material={nodes.Sphere006.material} position={[1.638, 0.074, -3.712]} rotation={[0, -Math.PI / 2, 0]} scale={[0.145, 0.108, 0.145]} />
        <mesh name="Plane210" geometry={nodes.Plane210.geometry} material={materials['Material.004']} position={[-0.029, 0.144, -5.784]} rotation={[-0.494, 0.633, -2.833]} scale={[-0.002, -0.285, -0.285]} />
        <mesh name="Sphere007" geometry={nodes.Sphere007.geometry} material={nodes.Sphere007.material} position={[-0.026, 0.074, -5.794]} rotation={[0, -Math.PI / 2, 0]} scale={[0.145, 0.108, 0.145]} />
        <mesh name="Circle029" geometry={nodes.Circle029.geometry} material={materials['material.002']} position={[3.419, 0.016, -6.008]} rotation={[0, -Math.PI / 2, 0]} scale={0.695} />
        <mesh name="Circle030" geometry={nodes.Circle030.geometry} material={materials['material.002']} position={[2.262, 0.016, -7.363]} rotation={[0, -Math.PI / 2, 0]} scale={0.499} />
        <mesh name="Circle031" geometry={nodes.Circle031.geometry} material={materials['material.002']} position={[4.028, 0.016, -8.033]} rotation={[0, -Math.PI / 4, 0]} scale={0.613} />
        <mesh name="Circle032" geometry={nodes.Circle032.geometry} material={materials.sprouts} position={[-0.457, 1.152, -4.762]} rotation={[0, -Math.PI / 2, 0]} scale={0.322} />
        <mesh name="Circle033" geometry={nodes.Circle033.geometry} material={materials.sprouts} position={[3.498, 0.944, -4.979]} rotation={[0, -Math.PI / 2, 0]} scale={0.375} />
        <mesh name="Circle034" geometry={nodes.Circle034.geometry} material={materials.sprouts} position={[-0.267, -0.074, -5.28]} rotation={[0, -Math.PI / 2, 0]} scale={0.363} />
        <mesh name="Circle035" geometry={nodes.Circle035.geometry} material={materials.sprouts} position={[3.495, -0.074, -7.229]} rotation={[0, -0.209, 0]} scale={0.717} />
        <mesh name="Sphere008" geometry={nodes.Sphere008.geometry} material={nodes.Sphere008.material} position={[-8.875, 0.074, -4.624]} rotation={[0, -Math.PI / 2, 0]} scale={[0.145, 0.108, 0.145]} />
        <mesh name="Sphere009" geometry={nodes.Sphere009.geometry} material={nodes.Sphere009.material} position={[-10.539, 0.074, -6.706]} rotation={[0, -Math.PI / 2, 0]} scale={[0.145, 0.108, 0.145]} />
        <mesh name="Circle036" geometry={nodes.Circle036.geometry} material={materials['material.002']} position={[-7.094, 0.016, -6.92]} rotation={[0, -Math.PI / 2, 0]} scale={0.695} />
        <mesh name="Circle037" geometry={nodes.Circle037.geometry} material={materials['material.002']} position={[-8.252, 0.016, -8.275]} rotation={[0, -Math.PI / 2, 0]} scale={0.499} />
        <mesh name="Circle038" geometry={nodes.Circle038.geometry} material={materials['material.002']} position={[-6.819, 0.016, -7.194]} rotation={[0, -Math.PI / 4, 0]} scale={0.613} />
        <mesh name="Circle039" geometry={nodes.Circle039.geometry} material={nodes.Circle039.material} position={[-7.016, 0.944, -5.891]} rotation={[0, -Math.PI / 2, 0]} scale={0.375} />
        <mesh name="Circle040" geometry={nodes.Circle040.geometry} material={materials.sprouts} position={[-7.018, -0.074, -8.141]} rotation={[0, -0.209, 0]} scale={0.717} />
        <mesh name="Plane280" geometry={nodes.Plane280.geometry} material={materials.Material} position={[0, -0.021, 0]} scale={15.86} />
        <mesh name="Circle041" geometry={nodes.Circle041.geometry} material={materials['material.002']} position={[-0.02, 0, -2.056]} scale={0.605} />
        <mesh name="Circle042" geometry={nodes.Circle042.geometry} material={materials['material.002']} position={[-3.823, 0, -5.45]} rotation={[-Math.PI, 0.593, -Math.PI]} scale={1.337} />
        <mesh name="Circle043" geometry={nodes.Circle043.geometry} material={materials['material.002']} position={[-0.821, 0, -4.708]} rotation={[0, Math.PI / 4, 0]} scale={0.653} />
        <mesh name="Circle044" geometry={nodes.Circle044.geometry} material={materials.sprouts} position={[0.589, 0.502, -1.345]} rotation={[Math.PI, -0.703, Math.PI]} scale={0.219} />
        <mesh name="Sphere010" geometry={nodes.Sphere010.geometry} material={nodes.Sphere010.material} position={[-0.39, 0.075, -3.941]} rotation={[0, Math.PI / 2, 0]} scale={[0.1, 0.075, 0.1]} />
        <mesh name="Sphere011" geometry={nodes.Sphere011.geometry} material={nodes.Sphere011.material} position={[-3.193, 0.075, -4.853]} rotation={[0, Math.PI / 2, 0]} scale={[0.1, 0.075, 0.1]} />
        <mesh name="Plane329" geometry={nodes.Plane329.geometry} material={materials['Material.001']} position={[-9.899, -0.005, -7.51]} rotation={[-Math.PI, 0.619, -Math.PI]} scale={[1.43, 0.751, 1.299]} />
        <mesh name="Plane330" geometry={nodes.Plane330.geometry} material={materials['Material.002']} position={[-8.171, 0.033, -7.258]} rotation={[0, -0.727, 0]} scale={-4.594} />
        <mesh name="Plane333" geometry={nodes.Plane333.geometry} material={materials['Material.002']} position={[-7.222, 0.029, -11.182]} rotation={[0, -0.727, 0]} scale={-4.594} />
        <mesh name="Plane334" geometry={nodes.Plane334.geometry} material={materials['Material.002']} position={[-7.222, 0.045, -11.182]} rotation={[0, -0.727, 0]} scale={-4.594} />
        <mesh name="Plane335" geometry={nodes.Plane335.geometry} material={materials['Material.002']} position={[-6.86, 0.029, -12.659]} rotation={[0, -0.727, 0]} scale={-4.594} />
        <mesh name="Plane340" geometry={nodes.Plane340.geometry} material={materials['Material.002']} position={[-7.245, 0.029, -13.177]} rotation={[0, -0.727, 0]} scale={-4.594} />
        <mesh name="Plane342" geometry={nodes.Plane342.geometry} material={materials['Material.002']} position={[-7.222, 0.029, -11.182]} rotation={[0, -0.727, 0]} scale={-4.594} />
        <mesh name="Plane343" geometry={nodes.Plane343.geometry} material={materials['Material.002']} position={[-7.222, 0.045, -11.182]} rotation={[0, -0.727, 0]} scale={-4.594} />
        <mesh name="Plane345" geometry={nodes.Plane345.geometry} material={materials['Material.002']} position={[-7.222, 0.029, -11.182]} rotation={[0, -0.727, 0]} scale={-4.594} />
        <mesh name="Plane346" geometry={nodes.Plane346.geometry} material={materials['Material.002']} position={[-7.222, 0.029, -11.182]} rotation={[0, -0.727, 0]} scale={-4.594} />
        <mesh name="Plane348" geometry={nodes.Plane348.geometry} material={materials['Material.002']} position={[-7.222, 0.029, -11.182]} rotation={[0, -0.727, 0]} scale={-4.594} />
        <mesh name="Plane353" geometry={nodes.Plane353.geometry} material={materials['Material.002']} position={[-7.222, 0.029, -11.182]} rotation={[0, -0.727, 0]} scale={-4.594} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/anime_like_waterbody.glb')

export default CustomClouds