/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\samay\OneDrive\Desktop\Hobbies_and_skills\dev\Sanatani@nimAtor\Sanatani@nimAtor_web\Animation_with_abhi\public\models\anime_clouds.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AnimeClouds(props) {
  const { nodes, materials } = useGLTF('/models/anime_clouds.glb')
  return (
    // eslint-disable-next-line react/no-unknown-property
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.clouds} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.clouds} position={[2.276, 0.075, -2.133]} />

    </group>
  )
}

useGLTF.preload('/models/anime_clouds.glb')

export default AnimeClouds
