/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\samay\OneDrive\Desktop\Hobbies_and_skills\dev\Sanatani@nimAtor\Sanatani@nimAtor_web\Animation_with_abhi\public\models\Hand.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Hand(props) {
  const { nodes, materials } = useGLTF('/models/Hand.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/models/Hand.glb')

export default Hand
