/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\samay\OneDrive\Desktop\Hobbies_and_skills\dev\Sanatani@nimAtor\Sanatani@nimAtor_web\Animation_with_abhi\public\models\perfume.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Perfume(props) {
  const { nodes, materials } = useGLTF('/models/perfume.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[0, 0, 1.025]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.002']} position={[0, 0, 1.025]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.marble} position={[0, 0.245, 1.025]} scale={[1, 1.019, 1]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Material} position={[0, 0, 1.025]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.34, 1.163, 1.025]} rotation={[-Math.PI, 0, 1.635]} scale={[-0.292, -1.261, -0.469]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.001']} position={[0.356, 1.064, 1.414]} rotation={[Math.PI / 2, -0.051, -Math.PI / 2]} scale={[0.102, 0.102, 0.27]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.005']} position={[4.859, 11.077, 1.407]} scale={1.838} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.marble} position={[0, -0.029, 1.025]} scale={[2.197, 2.24, 2.197]} />
    </group>
  )
}

useGLTF.preload('/models/perfume.glb')

export default Perfume